# Generated by Django 4.0.6 on 2022-07-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('content', models.TextField(verbose_name='Discription')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Photo')),
                ('year_of_birth', models.PositiveSmallIntegerField(verbose_name='Year of birth')),
                ('year_of_death', models.PositiveSmallIntegerField(default=False, verbose_name='Year of death')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time create')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time update')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
