# Generated by Django 4.0.6 on 2022-07-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='year_of_death',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Year of death'),
        ),
    ]
