# Generated by Django 4.0.6 on 2022-07-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0003_men_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='photo',
            field=models.ImageField(default=32, upload_to='photos/%Y/%m/%d', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='men',
            name='year_of_birth',
            field=models.PositiveSmallIntegerField(default=1990, verbose_name='Year of birth'),
        ),
        migrations.AlterField(
            model_name='men',
            name='year_of_death',
            field=models.PositiveSmallIntegerField(default=2022, verbose_name='Year of death'),
        ),
    ]
