# Generated by Django 4.0.6 on 2022-07-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0004_alter_men_photo_alter_men_year_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='age',
            field=models.PositiveSmallIntegerField(default=32, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='men',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Photo'),
        ),
    ]
