# Generated by Django 4.0.6 on 2022-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0005_alter_men_age_alter_men_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='year_of_death',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Year of death'),
        ),
    ]
