# Generated by Django 4.0.6 on 2022-07-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0006_alter_men_year_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='year_of_death',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of death'),
        ),
    ]
